baseURL = "https://dsaspark.org/"
languageCode = "en-us"
title = "DSA Spark"
theme = "hyde"
contentDir = "content"
publshDir = "/home/hugo/site"
author = "DSA Spark"
defaultLayout = "post"

[params]
  disqusShortname = "dsaspark"
  description = "It's Lit."
  copyright = "CC-BY-SA 4.0"
  author = ["Anton Johannsen", "J.R. Murray", "DSA Spark"]

[permalinks]
  post = "/:year/:month/:title/"

[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 4

[[menu.main]]
  name = "DSA Homepage"
  url = "http://dsausa.org"
  weight = 5
