baseURL = "https://dsaspark.org/"
languageCode = "en-us"
title = "DSA Spark"
theme = "hyde"
contentDir = "content"
publshDir = "public"
author = "DSA Spark"
defaultLayout = "post"

[params]
  disqusShortname = "dsaspark"
  description = "It's Lit."
  copyright = "CC-BY-SA 4.0"

[permalinks]
  post = "/:year/:month/:title/"

[[menu.main]]
  name = "Points of Unity"
  url = "/points-of-unity/"
  weight = 1

[[menu.main]]
  name = "Political Education"
  url = "/education/"
  weight = 2

[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 3